/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.ybar.checkcert;

import java.io.IOException;
import java.security.KeyPair;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bouncycastle.operator.OperatorCreationException;

/**
 *
 * @author slawka
 */
public class MainFrame extends javax.swing.JFrame {

    private static CheckCert cert = new CheckCert();
    private JFileChooser fileChooser = null;
    private static final FileNameExtensionFilter filterCer = new FileNameExtensionFilter("Certificate files *.cer", "cer");
    private static final FileNameExtensionFilter filterKey = new FileNameExtensionFilter("Key files *.key", "key");

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Daemon daemon = new Daemon();
        daemon.setjTable(jTable1);
        Thread thread = new Thread(daemon);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTypeCert = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonUpload = new javax.swing.JButton();
        jButtonDownload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;   //Disallow the editing of any cell
        }};
        jTextFieldCertName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDelId = new javax.swing.JTextField();
        jLabelDelId = new javax.swing.JLabel();
        jButtonDel = new javax.swing.JButton();
        jButtonUploadKey = new javax.swing.JButton();
        jButtonSaveCSR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jButtonCreateCSR = new javax.swing.JButton();
        jRadioButtonServerCert = new javax.swing.JRadioButton();
        jRadioButtonServerClient = new javax.swing.JRadioButton();
        jRadioButtonServerAll = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaIP = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDNS = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Cert");

        jButtonUpload.setText("Upload Cert");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        jButtonDownload.setText("Download Cert");
        jButtonDownload.setMaximumSize(new java.awt.Dimension(88, 23));
        jButtonDownload.setMinimumSize(new java.awt.Dimension(88, 23));
        jButtonDownload.setPreferredSize(new java.awt.Dimension(88, 23));
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(cert.listCertTable());
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.changeSelection(0, 0, false, false);
        jScrollPane1.setViewportView(jTable1);

        jTextFieldCertName.setToolTipText("Краткое описание сертификата");

        jLabel1.setText("Short description");

        jLabelDelId.setText("Del ID");
        jLabelDelId.setToolTipText("");

        jButtonDel.setText("Delete ID");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonUploadKey.setText("Upload Key");
        jButtonUploadKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadKeyActionPerformed(evt);
            }
        });

        jButtonSaveCSR.setText("Save CSR");
        jButtonSaveCSR.setMaximumSize(new java.awt.Dimension(88, 23));
        jButtonSaveCSR.setMinimumSize(new java.awt.Dimension(88, 23));
        jButtonSaveCSR.setPreferredSize(new java.awt.Dimension(88, 23));
        jButtonSaveCSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveCSRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDelId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(jButtonUpload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaveCSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUploadKey, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldCertName)
                    .addGap(125, 125, 125)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveCSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUploadKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDelId)
                        .addComponent(jTextFieldDelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("DB Cet", jPanel1);

        jLabel2.setText("CN = ");

        jTextFieldCN.setText("CN-Test");

        jLabel3.setText("OU = ");
        jLabel3.setToolTipText("");

        jTextFieldOU.setText("OU-Test");

        jLabel4.setText("O = ");

        jTextFieldO.setText("O-Test");

        jLabel5.setText("C = ");

        jTextFieldC.setText("C-Test");

        jButtonCreateCSR.setText("Create CSR");
        jButtonCreateCSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCSRActionPerformed(evt);
            }
        });

        buttonGroupTypeCert.add(jRadioButtonServerCert);
        jRadioButtonServerCert.setText("WWW server authentication");
        jRadioButtonServerCert.setActionCommand("server");

        buttonGroupTypeCert.add(jRadioButtonServerClient);
        jRadioButtonServerClient.setSelected(true);
        jRadioButtonServerClient.setText("WWW client authentication");
        jRadioButtonServerClient.setActionCommand("client");

        buttonGroupTypeCert.add(jRadioButtonServerAll);
        jRadioButtonServerAll.setText("WWW server and client authentication");
        jRadioButtonServerAll.setActionCommand("clientserver");

        jTextAreaIP.setColumns(20);
        jTextAreaIP.setRows(5);
        jTextAreaIP.setText("1.2.3.4\n4.3.2.1\n10.20.30.1");
        jScrollPane3.setViewportView(jTextAreaIP);

        jTextAreaDNS.setColumns(20);
        jTextAreaDNS.setRows(5);
        jTextAreaDNS.setText("test.com\ntest2.com\ntest3.com");
        jScrollPane4.setViewportView(jTextAreaDNS);

        jLabel6.setText("IP one in line");

        jLabel7.setText("DNS one in line");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonServerCert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonServerClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonServerAll)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldC)
                            .addComponent(jTextFieldO)
                            .addComponent(jTextFieldOU)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCN))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCreateCSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonServerCert)
                    .addComponent(jRadioButtonServerClient)
                    .addComponent(jRadioButtonServerAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addComponent(jButtonCreateCSR)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create CSR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadKeyActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();

        if (selectedRow.length < 1) {
            JOptionPane.showMessageDialog(MainFrame.this, "Select row Cert");
            return;
        } else {

            fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Select File");
            // Определение режима - только файл
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(filterKey);
            int result = fileChooser.showSaveDialog(MainFrame.this);
            // Если файл выбран, то представим его в сообщении
            if (result == JFileChooser.APPROVE_OPTION) {

                int dialogResult = JOptionPane.showConfirmDialog(MainFrame.this, "File '" + fileChooser.getSelectedFile() + " upload to id=" + jTable1.getValueAt(selectedRow[0], 0));
                if (dialogResult == JOptionPane.YES_OPTION) {
                    cert.uploadKey(fileChooser.getSelectedFile().toString(), (int) jTable1.getValueAt(selectedRow[0], 0));
                }
            }
            jTextFieldCertName.setText("");
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        }
    }//GEN-LAST:event_jButtonUploadKeyActionPerformed

    private void jButtonCreateCSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCSRActionPerformed
        //System.out.println("Selected Radio Button: " + buttonGroupTypeCert.getSelection().getActionCommand());
        //System.exit(0);
        try {
            cert.createCSR(jTextFieldCN.getText().trim(), jTextFieldOU.getText().trim(), jTextFieldO.getText().trim(), jTextFieldC.getText().trim(), jTextAreaDNS.getText().trim(), jTextAreaIP.getText().trim(), buttonGroupTypeCert.getSelection().getActionCommand());
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OperatorCreationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCreateCSRActionPerformed

    private void jButtonSaveCSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveCSRActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
        }
        fileChooser.setDialogTitle("Choosing a directory to save");
        // Определение режима - только каталог
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(MainFrame.this);
        // Если директория выбрана, покажем ее в сообщении
        if (result == JFileChooser.APPROVE_OPTION) {
            cert.saveCert((Integer) jTable1.getValueAt(selectedRow[0], 0), "CSR", fileChooser.getSelectedFile());
        }
    }//GEN-LAST:event_jButtonSaveCSRActionPerformed

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDownloadActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
        }
        fileChooser.setDialogTitle("Choosing a directory to save");
        // Определение режима - только каталог
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(MainFrame.this);
        // Если директория выбрана, покажем ее в сообщении
        if (result == JFileChooser.APPROVE_OPTION) {
            cert.saveCert((Integer) jTable1.getValueAt(selectedRow[0], 0), "CERT", fileChooser.getSelectedFile());
            cert.saveCert((Integer) jTable1.getValueAt(selectedRow[0], 0), "KEY", fileChooser.getSelectedFile());
        }
    }// GEN-LAST:event_jButtonDownloadActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUploadActionPerformed

        if (jTextFieldCertName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(MainFrame.this, "Enter Short description");
            return;
        } else {
            if (fileChooser == null) {
                fileChooser = new JFileChooser();
            }
            fileChooser.setDialogTitle("Выбор файла");
            // Определение режима - только файл
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(filterCer);
            int result = fileChooser.showSaveDialog(MainFrame.this);
            // Если файл выбран, то представим его в сообщении
            if (result == JFileChooser.APPROVE_OPTION) {
                cert.uploadCert(fileChooser.getSelectedFile().toString(), jTextFieldCertName.getText().trim());
                JOptionPane.showMessageDialog(MainFrame.this, "Файл '" + fileChooser.getSelectedFile() + " upload ");
            }
            jTextFieldCertName.setText("");
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        }
    }// GEN-LAST:event_jButtonUploadActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDelActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();
        String delId = jTextFieldDelId.getText().trim();
        String selectRow = jTable1.getValueAt(selectedRow[0], 0).toString();
        if (selectRow.equals(delId)) {
            cert.delCert((Integer) jTable1.getValueAt(selectedRow[0], 0));
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        } else {
            JOptionPane.showMessageDialog(MainFrame.this,
                    "Del ID and the selected row does not match\n" + "Del ID = |" + jTextFieldDelId.getText().trim()
                    + "|\n" + "Id Row = |" + jTable1.getValueAt(selectedRow[0], 0) + "|");
            return;
        }
    }// GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTypeCert;
    private javax.swing.JButton jButtonCreateCSR;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonSaveCSR;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JButton jButtonUploadKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonServerAll;
    private javax.swing.JRadioButton jRadioButtonServerCert;
    private javax.swing.JRadioButton jRadioButtonServerClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDNS;
    private javax.swing.JTextArea jTextAreaIP;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldCN;
    private javax.swing.JTextField jTextFieldCertName;
    private javax.swing.JTextField jTextFieldDelId;
    private javax.swing.JTextField jTextFieldO;
    private javax.swing.JTextField jTextFieldOU;
    // End of variables declaration//GEN-END:variables
}
