/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.ybar.checkcert;

import java.io.IOException;
import java.security.KeyPair;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bouncycastle.operator.OperatorCreationException;

/**
 *
 * @author slawka
 */
public class MainFrame extends javax.swing.JFrame {

    private static CheckCert cert = new CheckCert();
    private JFileChooser fileChooser = null;
    private static final FileNameExtensionFilter filterCer = new FileNameExtensionFilter("Certificate files *.cer", "cer");
    private static final FileNameExtensionFilter filterKey = new FileNameExtensionFilter("Key files *.key", "key");

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Daemon daemon = new Daemon();
        daemon.setjTable(jTable1);
        Thread thread = new Thread(daemon);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonUpload = new javax.swing.JButton();
        jButtonDownload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;   //Disallow the editing of any cell
        }};
        jTextFieldCertName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDelId = new javax.swing.JTextField();
        jLabelDelId = new javax.swing.JLabel();
        jButtonDel = new javax.swing.JButton();
        jButtonUploadKey = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jButtonCSR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCsrOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Cert");

        jButtonUpload.setText("Upload Cert");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        jButtonDownload.setText("Download Cert");
        jButtonDownload.setMaximumSize(new java.awt.Dimension(88, 23));
        jButtonDownload.setMinimumSize(new java.awt.Dimension(88, 23));
        jButtonDownload.setPreferredSize(new java.awt.Dimension(88, 23));
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(cert.listCertTable());
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.changeSelection(0, 0, false, false);
        jScrollPane1.setViewportView(jTable1);

        jTextFieldCertName.setToolTipText("Краткое описание сертификата");

        jLabel1.setText("Short description");

        jLabelDelId.setText("Del ID");
        jLabelDelId.setToolTipText("");

        jButtonDel.setText("Delete ID");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonUploadKey.setText("Upload Key");
        jButtonUploadKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadKeyActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(88, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(88, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(88, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelDelId)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDelId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCertName))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUploadKey, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUpload)
                        .addComponent(jTextFieldCertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUploadKey))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDelId)
                        .addComponent(jButtonDel))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("DB Cet", jPanel1);

        jLabel2.setText("CN = ");

        jTextFieldCN.setText("CN-Test");

        jLabel3.setText("OU = ");
        jLabel3.setToolTipText("");

        jTextFieldOU.setText("OU-Test");

        jLabel4.setText("O = ");

        jTextFieldO.setText("O-Test");

        jLabel5.setText("C = ");

        jTextFieldC.setText("C-Test");

        jButtonCSR.setText("Create CSR");
        jButtonCSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSRActionPerformed(evt);
            }
        });

        jTextAreaCsrOut.setColumns(20);
        jTextAreaCsrOut.setRows(5);
        jTextAreaCsrOut.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(jTextAreaCsrOut);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jButtonCSR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCN))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldC)
                            .addComponent(jTextFieldO)
                            .addComponent(jTextFieldOU, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create CSR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadKeyActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();

        if (selectedRow.length < 1) {
            JOptionPane.showMessageDialog(MainFrame.this, "Select row Cert");
            return;
        } else {

            fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Select File");
            // Определение режима - только файл
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(filterKey);
            int result = fileChooser.showSaveDialog(MainFrame.this);
            // Если файл выбран, то представим его в сообщении
            if (result == JFileChooser.APPROVE_OPTION) {

                int dialogResult = JOptionPane.showConfirmDialog(MainFrame.this, "File '" + fileChooser.getSelectedFile() + " upload to id=" + jTable1.getValueAt(selectedRow[0], 0));
                if (dialogResult == JOptionPane.YES_OPTION) {
                    cert.uploadKey(fileChooser.getSelectedFile().toString(), (int) jTable1.getValueAt(selectedRow[0], 0));
                }
            }
            jTextFieldCertName.setText("");
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        }
    }//GEN-LAST:event_jButtonUploadKeyActionPerformed

    private void jButtonCSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSRActionPerformed
        /*CSRGenerator csrGeneration = new CSRGenerator();

        csrGeneration.commonName = jTextFieldCN.getText().trim();
        csrGeneration.country = jTextFieldC.getText().trim();
        csrGeneration.organizationName = jTextFieldO.getText().trim();
        csrGeneration.organizationUnit = jTextFieldOU.getText().trim();
        
        // Generate key pair
        KeyPair keyPair = csrGeneration.generateKeyPair("RSA", 1024);
        System.out.println("KeyPair generated");

        byte[] csrData = csrGeneration.generateCSR("SHA256WithRSA", keyPair);

        jTextAreaCsrOut.setText(new String(csrData));
         */
    }//GEN-LAST:event_jButtonCSRActionPerformed

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDownloadActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
        }
        fileChooser.setDialogTitle("Choosing a directory to save");
        // Определение режима - только каталог
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(MainFrame.this);
        // Если директория выбрана, покажем ее в сообщении
        if (result == JFileChooser.APPROVE_OPTION) {
            cert.saveCert((Integer) jTable1.getValueAt(selectedRow[0], 0), fileChooser.getSelectedFile());
        }
    }// GEN-LAST:event_jButtonDownloadActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUploadActionPerformed

        if (jTextFieldCertName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(MainFrame.this, "Enter Short description");
            return;
        } else {
            if (fileChooser == null) {
                fileChooser = new JFileChooser();
            }
            fileChooser.setDialogTitle("Выбор файла");
            // Определение режима - только файл
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(filterCer);
            int result = fileChooser.showSaveDialog(MainFrame.this);
            // Если файл выбран, то представим его в сообщении
            if (result == JFileChooser.APPROVE_OPTION) {
                cert.uploadCert(fileChooser.getSelectedFile().toString(), jTextFieldCertName.getText().trim());
                JOptionPane.showMessageDialog(MainFrame.this, "Файл '" + fileChooser.getSelectedFile() + " upload ");
            }
            jTextFieldCertName.setText("");
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        }
    }// GEN-LAST:event_jButtonUploadActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDelActionPerformed
        int[] selectedRow = jTable1.getSelectedRows();
        String delId = jTextFieldDelId.getText().trim();
        String selectRow = jTable1.getValueAt(selectedRow[0], 0).toString();
        if (selectRow.equals(delId)) {
            cert.delCert((Integer) jTable1.getValueAt(selectedRow[0], 0));
            jTable1.setModel(cert.listCertTable());
            jTable1.repaint();
        } else {
            JOptionPane.showMessageDialog(MainFrame.this,
                    "Del ID and the selected row does not match\n" + "Del ID = |" + jTextFieldDelId.getText().trim()
                    + "|\n" + "Id Row = |" + jTable1.getValueAt(selectedRow[0], 0) + "|");
            return;
        }
    }// GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        CertificateAuthorityClientTest testC = new CertificateAuthorityClientTest();
        try {
            testC.createCSR();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OperatorCreationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCSR;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JButton jButtonUploadKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaCsrOut;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldCN;
    private javax.swing.JTextField jTextFieldCertName;
    private javax.swing.JTextField jTextFieldDelId;
    private javax.swing.JTextField jTextFieldO;
    private javax.swing.JTextField jTextFieldOU;
    // End of variables declaration//GEN-END:variables
}
